### ISSUE TITLE
Please add the Philippines

### ISSUE THREAD

**Issue by maning** [Stalfur/Askja#27]
Can you add my country?  I will be happy to curate and manage it.

**Comment by Stalfur** [comment]
Of course, North America is currently being processed, I'll make the Philippines first in line after that.

**Comment by maning** [comment]
Thanks!  As an initial list, it would be better to just focus on towns and cities.

**Comment by Stalfur** [comment]
No half measures taken here! [Philippines has been added](http://osm.hlidskjalf.is/settlements.php?idc=1) and is currently being processed, should be done later today. Those [8 that have no region](http://osm.hlidskjalf.is/settlements.php?idc=1&region=[no%20name]) might be something to take a look at, Nominatim did not find a match for them.

**Comment by Stalfur** [comment]
Mostly completed. Rest of updates will trickle in shortly.
